### ISSUE TITLE
Internationalization : English UI

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#13]
- [ ] Revamp current site so to use variable for french labels
- [ ] Translate FR file into EN (English) file

@0x010C, @xenophon75, @zmoostik : Do we have a specific file to translate ?

**Comment by hugolpz** [comment]
@Lyokoi @Xenophon75  Salut,
Je suis au Hackathon de Vienne et souhaite faire une démo en anglais . 
On as qque chose dans les tuyaux à déployer ???

**Comment by Lyokoi** [comment]
Une démo ? Des diapos ?

Stp, passe par l'adresse lyokoi@free.fr pour me contacter, c'est plus sûr.

Lucas

**Comment by wiese** [comment]
Hi,
I am at the hackathon in Vienna as well and picked up some tasks. Would you mind switching the communication/commit messages to English? Would make it much easier to follow. On the other hand, native French speakers would be the prime candidates to perform this ticket, creating English translation keys from the existing i18n and putting the French texts in the translation files... http://symfony.com/doc/current/translation.html

Cheers

**Comment by wiese** [comment]
To add to the discussion - I consider this ticket as more of an epic than a task because there are a couple of unanswered questions:

1. will there be an automatic guess of language to use (e.g. based on browser language)? *would recommend*
2. how will the language be persisted for a user between page requests? In a cookie? In the URL? *would recommend in the URL as the first part of the path, e.g. `/fr/sounds`*
3. will the URLs (path, query) also be translated depending on language? E.g. `/en/users` vs `/fr/utilisateur` *would not recommend*
4. given the domain of the tool, is it maybe a controversial over-simplification to limit the languages of the UI to plain-old ISO 639-1 Alpha-2?

**Comment by hugolpz** [comment]
Hello Wiese,
I think we will focus on English and French as of *right now*.

=> 3) : I'am deeply against url translations. Url human friendly yes, but in common language : English. Keep things simple.
=> 4) We are migrating to 639-1 Alpha-3. not sure its the best choice for linguists tho. Need to ask them.

**Comment by hugolpz** [comment]
@wiese. cc: @Lyokoi :
I received an **email from @Lyokoi**. Story short, Lucas (Lyokoi) recently tooks over a new job in new place and so is under work pressure from this side. So : 
- He can commit english / multilanguages support in by mid-June (realistic estimate but not sure)
- He explored the issue, only few things coded so far (20%?)
- recommend the native symphony translation tool.

@wiese, @ts : 
**As for the timeline + probability of execution and commit, we need a volunteer to take over and push that feature calmly, solidly, in the next 3 weeks ?** If so, please assign this issue to yourself.

----
**June 17th :** Worth noticing, Lucas mentioned me a LinguaLibre meeting which could create a new github milestone for motivational purpuses :haircut_woman: 

Lucas (@Lyokoi) & Nicolas (@zmoostik), as older contributors, will be asked to make code review, onboarding and share the software's architectural vision.

Also : Congratulation to Lucas for the new job and adventure :+1:

**Comment by hugolpz** [comment]
The feature was asked again on https://github.com/commons-app/apps-android-commons/issues/697

**Comment by hugolpz** [comment]
Per #73
