### ISSUE TITLE
 Internal Server Error upon removing a specific recording

### ISSUE THREAD

**Issue by kamomil** [wikimedia-france/Lingua-Libre#59]
when clicking on the X sign ("supprimer") [on a specific recording](https://lingualibre.fr/sounds/5774/show) (via my account) and then I click "confirmer" I get 

> Oops! An Error Occurred

>The server returned a "500 Internal Server Error".

>Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

This happen only for one  specific record. The rest are removed ok.

**Comment by hugolpz** [comment]
Which record ?

**Comment by kamomil** [comment]
on my account:
https://lingualibre.fr/sounds/5774/show

**Comment by hugolpz** [comment]
I see the record but i cannot see the delete cross button in "x" shape.

**Comment by hugolpz** [comment]
I see the record but i cannot see the delete cross button in "x" shape.
Likely because I'am not the author of this audio ( @zmoostik , can you confirm ?).
I tried [accessing this audio delete page via the relefant url](https://lingualibre.fr/sounds/5774/delete) but didn't work. I thus cannot test further.
