### ISSUE TITLE
Allow to select a CC-0 licence

### ISSUE THREAD

**Issue by pamputt** [wikimedia-france/Lingua-Libre#65]
In addition to the CC by-sa 4.0 licence, would it be possible to propose to licence its recordings under the CC-0 licence? I am not an expert on legal stuff but from my point of view, there is no intellectual property for such basic work.

**Comment by hugolpz** [comment]
There is by default copyright on voice, and it's a personal interpretation of a phonem / word / sentence.
I'am not sure CC-by-sa makes sense for our project. Especially since audios could be integrated to wikidata, which require CC-0.
Yet, CC-by-sa worked fine for previous similar project and encouraged speakers to record more since it provided visibility and notability to them.
I'am starting to think that a dual CC-by-sa-4.0 & CC-0 would be the best.

**Comment by pamputt** [comment]
Not sure at all there is copyright on voice,  because there is no creative work behind the recording but I understand it can be discussed. Anyway, it is not my interpretation and I personally licence my audio recording under CC-0 licence. A dual licence could be  a good solution.

**Comment by hugolpz** [comment]
To clarify, I suggest to :

- force the speaker to agree for a dual CC-by-sa + CC0
- so the end users can choose either one or the other.

This have been practiced on commons such as dual "GPL + CC-by-sa, pick the one you favor"

**Comment by pamputt** [comment]
Agreed with that.

**Comment by 0x010C** [comment]
Note that it's not required for a media to be CC0 to be linked on Wikidata. In fact, the large majority of the pictures linked in the P18 property (_image_) are not CC0.

**Comment by hugolpz** [comment]
Done.
![tutorial2](https://user-images.githubusercontent.com/1420189/40271600-51f9fb92-5b9f-11e8-9dfa-b7850d1fda37.png)
